name: moodthread
description: "BeReal for emotions — one sentence, once a day"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase - Updated to latest compatible versions
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.4.3
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  
  # State Management
  provider: ^6.1.1
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  flutter_local_notifications: ^16.3.0
  
  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
