// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Basic configuration for development - replace with real values from Firebase Console
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYotsCDkw1uOfuXpOneceKItFJUOSG7Wg',
    appId: '1:1048351012922:web:5ee8b94570d21752d55d03',
    messagingSenderId: '1048351012922',
    projectId: 'moodthread-97785',
    authDomain: 'moodthread-97785.firebaseapp.com',
    storageBucket: 'moodthread-97785.firebasestorage.app',
    measurementId: 'G-QHD46SM137',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYotsCDkw1uOfuXpOneceKItFJUOSG7Wg',
    appId: '1:1048351012922:web:5ee8b94570d21752d55d03',
    messagingSenderId: '1048351012922',
    projectId: 'moodthread-97785',
    storageBucket: 'moodthread-97785.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYotsCDkw1uOfuXpOneceKItFJUOSG7Wg',
    appId: '1:1048351012922:web:5ee8b94570d21752d55d03',
    messagingSenderId: '1048351012922',
    projectId: 'moodthread-97785',
    storageBucket: 'moodthread-97785.firebasestorage.app',
    iosClientId: 'demo-ios-client-id',
    iosBundleId: 'com.example.moodthread',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYotsCDkw1uOfuXpOneceKItFJUOSG7Wg',
    appId: '1:1048351012922:web:5ee8b94570d21752d55d03',
    messagingSenderId: '1048351012922',
    projectId: 'moodthread-97785',
    storageBucket: 'moodthread-97785.firebasestorage.app',
    iosClientId: 'demo-ios-client-id',
    iosBundleId: 'com.example.moodthread',
  );
}
